### ISSUE TITLE
请问可以添加emoji的支持吗？

### ISSUE THREAD

**Issue by RoachLin** [Liu-Junyan/youtube-livechat-to-danmaku#2]
视频链接：https://www.youtube.com/watch?v=TN--u8kgVM0
我使用[chat-downloader](https://github.com/xenova/chat-downloader)得到了json文件，第87行是含有emoji的信息，我尝试把emoji添加进去，但是无论是这样写“\ud83d\ude16”还是这样写“😖”，使用您的网站转换出来的字幕都没有包含emoji，看上去是直接被舍弃掉了，请问可以添加emoji的支持吗？

**Comment by Liu-Junyan** [comment]
已添加emotes相关功能。勾选“转换Emotes”后可以将标准emoji转换为Unicode，进而能够被播放器正确渲染。

**Comment by RoachLin** [comment]
完美解决，十分感谢！
